on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://ftp.franciscoigor.me/
        ftp-username: franciscoigor@franciscoigor.me
        local-dir: ./
        git-ftp-args: --remote-root /projects/laravel8-app
        ftp-password: ${{ secrets.franciscoigorme_ftp_password }}
